modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "mekanism_extras"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"

[[mixins]]
    config = "mekextra.mixins.json"
    description = '''${mod_description}'''

[[dependencies.mekanism_extras]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.mekanism_extras]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
